services:
  caddy_dev:
    profiles:
      - dev
    image: caddy:2
    restart: unless-stopped
    ports:
      - "${CADDY_HTTP_PORT:-80}:80"
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile:ro
    depends_on:
      - rosdev
      - mediamtx

  caddy_prod:
    profiles:
      - prod
    image: caddy:2
    restart: unless-stopped
    ports:
      - "${CADDY_HTTP_PORT:-80}:80"
    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile:ro
    depends_on:
      - nicegui
      - mediamtx

  nicegui:
    profiles:
      - prod
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    # network_mode: host
    expose: 
    - "${NICEGUI_PORT:-6969}"
    environment:
      - MTX_PATH=${MTX_PATH:-cam}
      - ROS_DOMAIN_ID=0
    # tty: true 
    # stdin_open: true
    # command: ["bash"]

  rosdev:
    profiles:
      - dev
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        USERNAME: kodifly
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    expose: 
    - "${NICEGUI_PORT:-6969}"
    environment:
      - MTX_PATH=${MTX_PATH:-cam}
      - ROS_DOMAIN_ID=0    
    volumes:
      - ../ros2_ws:/home/kodifly/ros2_ws
    working_dir: /home/kodifly/ros2_ws
    tty: true
    stdin_open: true
  mediamtx:
    profiles:
      - dev
      - prod
    image: bluenviron/mediamtx:1.15.6
    restart: unless-stopped
    volumes:
      - ./mediamtx.yaml:/mediamtx.yml:ro
    expose:
      - "8889"
    ports:
      - "8554:8554"
      - "${WEBRTC_UDP_PORT:-8189}:8189/udp"
    environment:
      # override: paths.cam.source
      - MTX_PATHS_CAM_SOURCE=${RTSP_SOURCE}
      - MTX_PATHS_CAM_RTSPTRANSPORT=tcp
      # override: webrtcAdditionalHosts (comma-separated list)
      - MTX_WEBRTCADDITIONALHOSTS=${PUBLIC_HOST},${LAN_HOST}